package org.thegalactic.lattice {
    class Permutation {
        -int length
        -int[] content
        .. Constructors ..
        +Permutation(int n)
        .. Accessors ..
        +int getLength()
        +int[] getContent()
        .. Mutators ..
        +boolean setLength()
        +Permutation setContent()
        .. Transformers ..
        +String toString()
        .. Predicates ..
        +boolean equals(Permutation s)
        +int hashCode()
    }
}
