package org.thegalactic.dgraph {
    class Edge {
        -Node from
        -Node to
        -Object content
        .. Constructors ..
        +Edge(final Node from, final Node to, final Object content)
        +Edge(final Node from, final Node to)
        .. Accessors ..
        +Node getFrom()
        +Node getTo()
        +Object getContent()
        .. Mutators ..
        +Edge setContent(final Object content)
        .. Predicates ..
        +boolean hasContent()
        .. Transformers ..
        +String toString()
        .. Comparators ..
        +boolean equals(final Object object);
        +int hashCode()
        +int compareTo(final Object object)
    }

    Edge *-- "2" Node
}
