package org.thegalactic.context.io {
    class Burmeister {
    	-{static}Burmeister instance
        +void read(Context context, BufferedReader file)
        +void write(Context context, BufferedWriter file)
        +{static}Burmeister getInstance()
        +{static}void register()
    }

    org.thegalactic.io.Reader <|-- Burmeister
    org.thegalactic.io.Writer <|-- Burmeister
}
