package org.thegalactic.context.io {
    class BurmeisterSerializer {
    	-{static}BurmeisterSerializer instance
        +void read(Context context, BufferedReader file)
        +void write(Context context, BufferedWriter file)
        +{static}BurmeisterSerializer getInstance()
        +{static}void register()
    }

    org.thegalactic.io.Reader <|-- BurmeisterSerializer
    org.thegalactic.io.Writer <|-- BurmeisterSerializer
}
