package org.thegalactic.context.io {
    class CsvSerializer {
    	-{static}CsvSerializer instance
        +void read(Context context, BufferedReader file)
        +void write(Context context, BufferedWriter file)
        +{static}CsvSerializer getInstance()
        +{static}void register()
    }

    org.thegalactic.io.Reader <|-- CsvSerializer
    org.thegalactic.io.Writer <|-- CsvSerializer
}
