package org.thegalactic.lattice.io {
    class ArrowRelationWriterFactory {
    	-{static}HashMap<String, ArrowRelationWriter> writers
        +{static}ArrowRelationWriter register(ArrowRelationWriter writer, String extension)
        +{static}ArrowRelationWriter unregister(String extension)
        +{static}ArrowRelationWriter get(String extension)
    }

    ArrowRelationWriterFactory o-- ArrowRelationWriter
}
