package org.thegalactic.lattice.io {
    class ArrowRelationWriterTeX {
    	-{static}ArrowRelationWriterTeX instance
        +void write(ArrowRelation arrow, BufferedWriter file)
        +{static}ArrowRelationWriterTeX getInstance()
        +{static}void register()
    }

    ArrowRelationWriter <|-- ArrowRelationWriterTeX
}
