package org.thegalactic.lattice.io {
    class ImplicationalSystemWriterText {
    	-{static}ImplicationalSystemWriterText instance
        +void write(ImplicationalSystem system, BufferedWriter file)
        +{static}ImplicationalSystemWriterText getInstance()
        +{static}void register()
    }

    ImplicationalSystemWriter <|-- ImplicationalSystemWriterText
}
