package fr.kbertet.lattice.io {
    class ContextWriterFactory {
    	-{static}HashMap<String, fr.kbertet.io.Writer<Context>> writers
        +{static}fr.kbertet.io.Writer<Context> register(fr.kbertet.io.Writer<Context> writer, String extension)
        +{static}fr.kbertet.io.Writer<Context> unregister(String extension)
        +{static}fr.kbertet.io.Writer<Context> get(String extension)
    }

    ContextWriterFactory o-- fr.kbertet.io.Writer
}
