package fr.kbertet.lattice.io {
    class ContextWriterCsv {
    	-{static}ContextWriterCsv instance
        +void write(Context context, BufferedWriter file)
        +{static}ContextWriterCsv getInstance()
        +{static}void register()
    }

    fr.kbertet.io.Writer <|-- ContextWriterCsv
}
