package fr.kbertet.lattice.io {
    class ContextReaderFactory {
    	-{static}HashMap<String, fr.kbertet.io.Reader<Context>> readers
        +{static}fr.kbertet.io.Reader<Context> register(fr.kbertet.io.Reader<Context> reader, String extension)
        +{static}fr.kbertet.io.Reader<Context> unregister(String extension)
        +{static}fr.kbertet.io.Reader<Context> get(String extension)
    }

    ContextReaderFactory o-- fr.kbertet.io.Reader
}
