package fr.kbertet.context.io {
    class Csv {
    	-{static}Csv instance
        +void read(Context context, BufferedReader file)
        +void write(Context context, BufferedWriter file)
        +{static}Csv getInstance()
        +{static}void register()
    }

    fr.kbertet.io.Reader <|-- Csv
    fr.kbertet.io.Writer <|-- Csv
}
