package org.thegalactic.dgraph {
    class Node {
        -int identifier
        -Object content
        -{static} int count = 0
        .. Constructors ..
        +Node(final Object content)
        +Node()
        .. Creators ..
        +Node clone()
        .. Accessors ..
        +int getIdentifier()
        +Object getContent()
        .. Mutators ..
        +Node setContent(final Object content)
        .. Transformers ..
        +String toString()
        .. Comparators ..
        +boolean equals(final Object object)
        +int hashCode()
        +int compareTo(final Object object)
    }
}
