package fr.kbertet.dgraph.io {
    class DGraphWriterDot {
    	-{static}DGraphWriterDot instance
        +void write(DGraph graph, BufferedWriter file)
        +{static}DGraphWriterDot getInstance()
        +{static}void register()
    }

    DGraphWriter <|-- DGraphWriterDot
}
