package fr.kbertet.context.io {
    class Burmeister {
    	-{static}Burmeister instance
        +void read(Context context, BufferedReader file)
        +void write(Context context, BufferedWriter file)
        +{static}Burmeister getInstance()
        +{static}void register()
    }

    fr.kbertet.io.Reader <|-- Burmeister
    fr.kbertet.io.Writer <|-- Burmeister
}
