package lattice {
    class ArrowRelation {
        .. Constructors ..
        +ArrowRelation(Lattice lattice)
        .. Transformers ..
        +void writeLaTex(String filename)
    }

    DGraph <|-- ArrowRelation
}
