package lattice {
    class ArrowRelation {
        .. Constructors ..
        +ArrowRelation(Lattice lattice)
        .. Transformers ..
        +void writeLaTex(String filename)
        .. Operations ..
        +Context getDoubleArrowTable()
        +Context getDoubleCircArrowTable()
    }

    DGraph <|-- ArrowRelation
}
