package lattice {
    class ComparableSet {
        .. Constructors ..
        +ComparableSet()
        +ComparableSet(TreeSet<Comparable> set)
        .. Transformers ..
        +String toString()
        .. Generators ..
        +ComparableSet copy()
        .. Comparators ..
        +boolean equals(Object object)
        +int hashCode()
        +int compareTo(Object object)
    }
}
