package lattice {
    class ConceptLatticeWriterFactory {
    	-{static}HashMap<String, ConceptLatticeWriter> writers
        +{static}ConceptLatticeWriter register(ConceptLatticeWriter writer, String extension)
        +{static}ConceptLatticeWriter unregister(String extension)
        +{static}ConceptLatticeWriter get(String extension)
    }

    ConceptLatticeWriterFactory o-- ConceptLatticeWriter
}
