package lattice {
    class ContextReaderText {
    	-{static}ContextReaderText instance
        +void read(Context context, BufferedReader file)
        +{static}ContextReaderText getInstance()
        +{static}void register()
    }

    ContextReader <|-- ContextReaderText
}
