package lattice {
    class ContextWriterFactory {
    	-{static}HashMap<String, ContextWriter> writers
        +{static}ContextWriter register(ContextWriter writer, String extension)
        +{static}ContextWriter unregister(String extension)
        +{static}ContextWriter get(String extension)
    }

    ContextWriterFactory o-- ContextWriter
}
