package lattice {
    class Couple {
        -Object left
        -Object right
        .. Constructors ..
        +Couple(Object l, Object r)
        .. Accessors ..
        +Object getLeft()
        +Object getRight()
        .. Mutators ..
        +void setLeft(Object left)
        +void setRight(Object right)
        .. Transformers ..
        +String toString()
        .. Predicates ..
        +boolean equals(Couple c)
        +int hashCode()
    }
}
