package lattice {
    class ImplicationalSystemReaderText {
    	-{static}ImplicationalSystemReaderText instance
        +void read(ImplicationalSystem system, BufferedReader file)
        +{static}ImplicationalSystemReaderText getInstance()
        +{static}void register()
    }

    ImplicationalSystemReader <|-- ImplicationalSystemReaderText
}
