package lattice;

/*
 * ImplicationalSystem.java
 *
 * Copyright: 2013 University of La Rochelle, France
 *
 * License: http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html CeCILL-B license
 *
 * This file is part of lattice, free package. You can redistribute it and/or modify
 * it under the terms of CeCILL-B license.
 *
 * @author Karell Bertet
 * @version 2013
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Collection;
import java.util.StringTokenizer;
import java.util.TreeMap;
import java.util.TreeSet;
import dgraph.DGraph;
import dgraph.Edge;
import dgraph.Node;

/**
 * This class gives a representation for an implicational system (ImplicationalSystem), a set of rules.
 *
 * An ImplicationalSystem is composed of a treeset of comparable elements, and a treeset of rules
 * defined by class {@link Rule}.
 *
 * This class provides methods implementing classical transformation of an implicational system :
 * make proper, make minimum, make right maximal, make left minimal, make unary,
 * make canonical basis, make canonical direct basis and reduction.
 *
 * An implicational system owns properties of a closure system, and thus extends the abstract class
 * {@link ClosureSystem} and implements methods {@link #getSet} and {@link #closure}.
 *
 * Therefore, the closed set lattice of an ImplicationalSystem can be generated by invoking method {@link #closedSetLattice} of a closure system.
 *
 * An implicational system can be instancied from and save to a text file in the following format:
 * - a list of elements separated by a space in the first line ;
 * - then, each rule on a line, written like [premise] -> [conclusion]
 *   where elements are separated by a space.
 *
 * ~~~
 * a b c d e
 * a b -> c d
 * c d -> e
 * ~~~
 *
 * ![ImplicationalSystem](ImplicationalSystem.png)
 *
 * @uml ImplicationalSystem.png
 * !include src/lattice/ImplicationalSystem.iuml
 * !include src/lattice/ClosureSystem.iuml
 *
 * hide members
 * show ImplicationalSystem members
 * class ImplicationalSystem #LightCyan
 * title ImplicationalSystem UML graph
 *
 * @todo  Standardize "count" method names
 */
public class ImplicationalSystem extends ClosureSystem {
    /*--------------- FIELDS -----------------*/

    /**
     * For the implicational rules of this component.
     */
    private TreeSet<Rule> sigma;

    /**
     * For the elements space of this component.
     */
    private TreeSet<Comparable> set;

    /* --------------- CONSTRUCTORS -----------*/

    /**
     * Constructs a new empty component.
     */
    public ImplicationalSystem() {
        this.sigma = new TreeSet<Rule>();
        this.set = new TreeSet<Comparable>();
    }

    /**
     * Constructs this component from the specified set of rules `sigma`.
     *
     * @param   sigma  the set of rules.
     */
    public ImplicationalSystem(Collection<Rule> sigma) {
        this.sigma = new TreeSet<Rule>(sigma);
        this.set = new TreeSet<Comparable>();
        for (Rule r : this.sigma) {
            set.addAll(r.getPremise());
            set.addAll(r.getConclusion());
        }
    }

    /**
     * Constructs this component as a copy of the specified IS `s`.
     *
     * Only structures (conataining reference of indexed elements) are copied.
     *
     * @param   s  the implicational system to be copied
     */
    public ImplicationalSystem(ImplicationalSystem s) {
        this.sigma = new TreeSet<Rule>(s.getRules());
        this.set = new TreeSet<Comparable>(s.getSet());
    }

    /**
     * Constructs this component from the specified file.
     *
     * The file have to respect a certain format:
     *
     * An implicational system can be instancied from and save to a text file in the following format:
     * - A list of elements separated by a space in the first line ;
     * - then, each rule on a line, written like [premise] -> [conclusion]
     *   where elements are separated by a space.
     *
     * ~~~
     * a b c d e
     * a b -> c d
     * c d -> e
     * ~~~
     *
     * Each element must be declared on the first line, otherwise, it is not added in the rule
     * Each rule must have a non empty concusion, otherwise, it is not added in the component
     *
     * @param   filename  the name of the file
     */
    public ImplicationalSystem(String filename) {
        try {
            this.sigma = new TreeSet<Rule>();
            this.set = new TreeSet<Comparable>();
            BufferedReader file = new BufferedReader(new FileReader(filename));
            // first line : All elements of S separated by a space
            // a StringTokenizer is used to divide the line into different token,
            // considering spaces as separator.
            StringTokenizer st =  new StringTokenizer(file.readLine());
            while (st.hasMoreTokens()) {
                String n = new String(st.nextToken());
                this.addElement(n);
            }
            // next lines : [elements of the premise separated by a space] -> [elements of the conclusion separated by a space]
            // a StringTokenizer is used to divide each rule.
            String line = file.readLine();
            while (!(line == null) && !line.isEmpty()) {
                st = new StringTokenizer(line);
                Rule r = new Rule();
                boolean prem = true;
                while (st.hasMoreTokens()) {
                    String word = st.nextToken();
                    if (word.equals("->")) {
                        prem = false;
                    } else {
                        String x = null;
                        // search of x in S
                        for (Comparable e : this.set) {
                            if (((String) e).equals(word)) {
                                x = (String) e;
                            }
                        }
                        if (x != null) {
                            if (prem) {
                                r.addToPremise(x);
                            } else {
                            r.addToConclusion(x);
                            }
                        }
                    }
                }
                if (!r.getConclusion().isEmpty()) {
                    this.addRule(r);
                }
                line = file.readLine();
            }
            file.close();
        } catch (Exception e) { e.printStackTrace(); }
    }

    /**
     * Generates a random ImplicationalSystem with a specified number of nodes and rules.
     *
     * @param   nbS  the number of nodes of the generated ImplicationalSystem
     * @param   nbR  the number of rules of the generated ImplicationalSystem
     *
     * @return  a random implicational system with a specified number of nodes and rules.
     */
    public static ImplicationalSystem random(int nbS, int nbR) {
        ImplicationalSystem sigma = new ImplicationalSystem();
        // addition of elements
        for (int i = 0; i < nbS; i++) {
            sigma.addElement(new Integer(i));
        }
        // addition of rules
        //for (int i = 0; i < nbR; i++) { One could get twice the same rule ...
        while (sigma.getRules().size() < nbR) {
            ComparableSet conclusion = new ComparableSet();
            int choice = (int) Math.rint(nbS * Math.random());
            int j = 1;
            for (Comparable c : sigma.getSet()) {
                if (j == choice) {
                    conclusion.add(c);
                }
                j++;
            }
            ComparableSet premisse = new ComparableSet();
            for (Comparable c : sigma.getSet()) {
                choice = (int) Math.rint(nbS * Math.random());
                if (choice < nbS / 5) {
                    premisse.add(c);
                }
            }
            sigma.addRule(new Rule(premisse, conclusion));
        }
        return sigma;
    }

    /* ------------- ACCESSORS METHODS ------------------ */

    /**
     * Returns the set of rules.
     *
     * @return  the set of rules of this component.
     */
    public TreeSet<Rule> getRules() {
        return this.sigma;
    }

    /**
     * Returns the set of indexed elements.
     *
     * @return  the elements space of this component.
     */
    public TreeSet<Comparable> getSet() {
        return this.set;
    }

    /**
     * Returns the number of elements in the set S of this component.
     *
     * @return  the number of elements in the elements space of this component.
     */
    public int nbElements() {
        return this.set.size();
    }

    /**
     * Returns the number of rules of this component.
     *
     * @return  the number of rules of this component.
     */
    public int nbRules() {
        return this.sigma.size();
    }

    /* ------------- MODIFICATION METHODS ------------------ */

    /**
     * Adds the specified element to the set `S` of this component.
     *
     * @param   e  the comparable to be added
     *
     * @return  true if the element has been added to `S`
     */
    public boolean addElement(Comparable e) {
        return set.add(e);
    }

    /**
     * Adds the specified element to the set `S` of this component.
     *
     * @param   x  the treeset of comparable to be added
     *
     * @return  true if the element has been added to `S`
     */
    public boolean addAllElements(TreeSet<Comparable> x) {
        boolean all = true;
        for (Comparable e : x) {
            if (!set.add(e)) {
                all = false;
            }
        }
        return all;
    }

    /**
     * Delete the specified element from the set `S` of this component and from all the rule containing it.
     *
     * @param   e  the comparable to be added
     *
     * @return true if the element has been added to `S`
     */
    public boolean deleteElement(Comparable e) {
        if (set.contains(e)) {
            set.remove(e);
            ImplicationalSystem sauv = new ImplicationalSystem(this);
            for (Rule r: sauv.sigma) {
                Rule newR = new Rule(r.getPremise(), r.getConclusion());
                newR.removeFromPremise(e);
                newR.removeFromConclusion(e);
                if (!r.equals(newR)) {
                    if (newR.getConclusion().size() != 0) {
                        this.replaceRule(r, newR);
                    } else {
                        this.removeRule(r);
                    }
                }
            }
            return true;
        }
        return false;
    }

    /**
     * Checks if the set S of this component contains the elements of the specified rule.
     *
     * @param   r  the rule to be checked
     *
     * @return  true if `S` contains all the elements of the rule
     */
    public boolean checkRuleElements(Rule r) {
        for (Object e : r.getPremise()) {
            if (!set.contains(e)) {
                return false;
            }
        }
        for (Object e : r.getConclusion()) {
            if (!set.contains(e)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Checks if this component already contains the specified rule.
     *
     * Rules are compared according to their premise and conclusion
     *
     * @param   r  the rule to be tested
     *
     * @return true if `sigma` contains the rule
     */
    public boolean containsRule(Rule r) {
        return this.sigma.contains(r);
    }

    /**
     * Adds the specified rule to this component.
     *
     * @param   r  the rule to be added
     *
     * @return  true the rule has been added to if `sigma`
     */
    public boolean addRule(Rule r) {
        if (!this.containsRule(r) && this.checkRuleElements(r)) {
            return this.sigma.add(r);
        }
        return false;
    }

    /**
     * Removes the specified rule from the set of rules of this component.
     *
     * @param   r  the rule to be removed
     *
     * @return  true if the rule has been removed
     */
    public boolean removeRule(Rule r) {
        return this.sigma.remove(r);
    }

    /**
     * Replaces the first specified rule by the second one.
     *
     * @param   r1  the rule to be replaced by `r2`
     * @param   r2  the replacing rule
     *
     * @return  true the rule has been replaced
     */
    public boolean replaceRule(Rule r1, Rule r2) {
        return (this.removeRule(r1) && this.addRule(r2));
    }

    /*-----------  SAVING METHODS -------------------- */

    /**
     * Returns a string representation of this component.
     *
     * The following format is used:
     *
     * An implicational system can be instancied from and save to a text file in the following format:
     * - A list of elements separated by a space in the first line ;
     * - then, each rule on a line, written like [premise] -> [conclusion]
     *   where elements are separated by a space.
     *
     * ~~~
     * a b c d e
     * a b -> c d
     * c d -> e
     * ~~~
     *
     * @return  a string representation of this component.
     */
    public String toString() {
        StringBuffer s = new StringBuffer();
        // first line : All elements of S separated by a space
        // a StringTokenizer is used to delete spaces in the
        // string description of each element of S
        for (Comparable e : this.set) {
            StringTokenizer st = new StringTokenizer(e.toString());
            while (st.hasMoreTokens()) {
                s.append(st.nextToken());
            }
            s.append(" ");
        }
        s.append("\n");
        // next lines : a rule on each line, described by:
        // [elements of the premise separated by a space] -> [elements of the conclusion separated by a space]
        for (Rule r : this.sigma) {
            s.append(r.toString()).append("\n");
        }
        return s.toString();
    }

    /**
     * Saves this component in a file which name is specified.
     *
     * The following format is used:
     *
     * An implicational system can be instancied from and save to a text file in the following format:
     * A list of elements separated by a space in the first line ;
     * then, each rule on a line, written like [premise] -> [conclusion]
     * where elements are separated by a space.
     *
     * ~~~
     * a b c d e
     * a b -> c d
     * c d -> e
     * ~~~
     *
     * @param   filename  the name of the file
     */
    public void toFile(String filename) {
        try {
            BufferedWriter file = new BufferedWriter(new FileWriter(filename));
            file.write(this.toString());
            file.close();
        } catch (Exception e) { e.printStackTrace(); }
    }

    /*-----------  PROPERTIES TEST METHODS -------------------- */

    /**
     * Returns true if this component is a proper ImplicationalSystem.
     *
     * This test is perfomed in O(|Sigma||S|) by testing conclusion of each rule
     *
     * @return  true if and only if this component is a proper implicational system.
     */
    public boolean isProper() {
        for (Rule r : this.sigma) {
            if (r.getPremise().contains(r.getConclusion())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns true if this component is an unary ImplicationalSystem.
     *
     * This test is perfomed in O(|Sigma||S|) by testing conclusion of each rule
     *
     * @return  true if this component is an unary ImplicationalSystem.
     */
    public boolean isUnary() {
        for (Rule r : this.sigma) {
            if (r.getConclusion().size() > 1) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns true if this component is a compact ImplicationalSystem.
     *
     * This test is perfomed in O(|Sigma|^2|S|) by testing premises of each pair of rules
     *
     * @return  true if this component is a compact ImplicationalSystem.
     */
    public boolean isCompact() {
        for (Rule r1 : this.sigma) {
            for (Rule r2: this.sigma) {
                if (!r1.equals(r2) && (r1.getPremise().equals(r2.getPremise()))) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Returns true if conclusion of rules of this component are closed.
     *
     * This test is perfomed in O(|Sigma||S|) by testing conclusion of each rule
     *
     * @return  true if conclusion of rules of this component are closed.
     */
    public boolean isRightMaximal() {
        for (Rule r : this.sigma) {
            if (!r.getConclusion().equals(this.closure(r.getConclusion()))) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns true if this component is left minimal.
     *
     * This test is perfomed in O(|Sigma|^2|S|) by testing conclusions of each pair of rules
     *
     * @return  true if this component is left minimal.
     */
    public boolean isLeftMinimal() {
        for (Rule r1 : this.sigma) {
            for (Rule r2 : this.sigma) {
                if (!r1.equals(r2) && r1.getPremise().containsAll(r2.getPremise()) && r1.getConclusion().equals(r2.getConclusion())) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Returns true if this component is direct.
     *
     * This test is perfomed in O(|Sigma|^2|S|) by testing if closure of
     * the premisse of each conclusion can be obtained by only one iteration
     * on the set of rules.
     *
     * @return  true if this component is direct.
     */
    public boolean isDirect() {
        for (Rule r1 : this.sigma) {
            TreeSet<Comparable> onePass = new TreeSet(r1.getPremise());
            for (Rule r2 : this.sigma) {
                if (r1.getPremise().containsAll(r2.getPremise())) {
                    onePass.addAll(r2.getConclusion());
                }
            }
            if (!onePass.equals(this.closure(r1.getPremise()))) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns true if this component is minimum.
     *
     * This test is perfomed in O(|Sigma|^2|S|) by testing if closure of
     * the premisse of each conclusion can be obtained by only one iteration
     * on the set of rules.
     *
     * @return  true if this component is minimum.
     */
    public boolean isMinimum() {
        ImplicationalSystem tmp = new ImplicationalSystem(this);
        tmp.makeRightMaximal();
        for (Rule r : sigma) {
            ImplicationalSystem epsylon = new ImplicationalSystem(tmp);
            epsylon.removeRule(r);
            TreeSet<Comparable> clThis = this.closure(r.getPremise());
            TreeSet<Comparable> clEpsilon = epsylon.closure(r.getPremise());
            if (clThis.equals(clEpsilon)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns true if this component is equal to its canonical direct basis.
     *
     * The canonical direct basis is computed before to be compare with this component.
     *
     * This test is performed in O(d|S|), where d corresponds to the number of rules
     * that have to be added by the direct treatment. This number is exponential in the worst case.
     *
     * @return  true if this component is equal to its canonical direct basis.
     */
    public boolean isCanonicalDirectBasis() {
        ImplicationalSystem cdb = new ImplicationalSystem(this);
        cdb.makeCanonicalDirectBasis();
        return (this.isIncludedIn(cdb) && cdb.isIncludedIn(this));
    }

    /**
     * Returns true if this component is equal to its canonical basis.
     *
     * The canonical basis is computed before to be compare with this component.
     *
     * This treatment is performed in (|Sigma||S|cl) where O(cl) is the
     * computation of a closure.
     *
     * @return  true if this component is equal to its canonical basis.
     */
    public boolean isCanonicalBasis() {
        ImplicationalSystem cb = new ImplicationalSystem(this);
        cb.makeCanonicalBasis();
        return (this.isIncludedIn(cb) && cb.isIncludedIn(this));
    }

    /**
     * Compares by inclusion of the proper and unary form of this component with the specified one.
     *
     * @param   is  another ImplicationalSystem
     *
     * @return  true if really include in this componenet.
     */
    public boolean isIncludedIn(ImplicationalSystem is) {
        ImplicationalSystem tmp = new ImplicationalSystem(this);
        tmp.makeProper();
        tmp.makeUnary();
        is.makeProper();
        is.makeUnary();
        for (Rule r : tmp.sigma) {
            if (!is.containsRule(r)) {
                return false;
            }
        }
        return true;
    }

    /*-----------  PROPERTIES MODIFICATION METHODS -------------------- */

    /**
     * Makes this component a proper ImplicationalSystem.
     *
     * Elements that are at once in the conclusion and in the premise are deleted from the conclusion.
     * When the obtained conclusion is an empty set, the rule is deleted from this component
     *
     * This treatment is performed in O(|Sigma||S|).
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeProper() {
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r : sauv.sigma) {
            // deletes elements of conclusion which are in the premise
            Rule newR = new Rule(r.getPremise(), r.getConclusion());
            for (Object e : r.getConclusion()) {
                if (newR.getPremise().contains(e)) {
                    newR.removeFromConclusion(e);
                }
            }
            // replace the rule by the new rule is it has been modified
            if (!r.equals(newR)) {
                this.replaceRule(r, newR);
            }
            // delete rule with an empty conclusion
            if (newR.getConclusion().isEmpty()) {
                this.removeRule(newR);
            }
        }
        return sauv.nbRules() - this.nbRules();
    }

    /**
     * Makes this component an unary ImplicationalSystem.
     *
     * This treatment is performed in O(|Sigma||S|)
     *
     * A rule with a non singleton as conclusion is replaced with a sets of rule, one rule for each
     * element of the conclusion.
     *
     * This treatment is performed in O(|Sigma||S|).
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeUnary() {
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r : sauv.sigma) {
            if (r.getConclusion().size() > 1) {
                this.removeRule(r);
                TreeSet<Comparable> conclusion = r.getConclusion();
                TreeSet<Comparable> premise = r.getPremise();
                for (Comparable e : conclusion) {
                    TreeSet<Comparable> newC = new TreeSet();
                    newC.add(e);
                    Rule nr = new Rule(premise, newC);
                    this.addRule(nr);
                }
            }
        }
        return sauv.nbRules() - this.nbRules();
    }

    /**
     * Replaces rules of same premise by only one rule.
     *
     * This treatment is performed in O(|sigma|^2|S|)
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeCompact() {
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r1 : sauv.sigma) {
            if (this.containsRule(r1)) {
                ComparableSet newConc = new ComparableSet();
                for (Rule r2 : sauv.sigma) {
                    if (this.containsRule(r2) && !r1.equals(r2) && (r1.getPremise().equals(r2.getPremise()))) {
                        newConc.addAll(r2.getConclusion());
                        boolean res = this.sigma.remove(r2);
                    }
                }
                if (newConc.size() > 0) {
                    newConc.addAll(r1.getConclusion());
                    Rule newR = new Rule(r1.getPremise(), newConc);
                    if (!r1.equals(newR)) {
                        this.replaceRule(r1, newR);
                    }
                }
            }
        }
        return sauv.nbRules() - this.nbRules();
    }

    /**
     * Replaces conclusion of each rule with their closure without the premise.
     *
     * This treatment is performed in O(|sigma||S|cl), where O(cl) is the
     * computation of a closure.
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeRightMaximal() {
        int s = this.nbRules();
        this.makeCompact();
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r : sauv.sigma) {
            Rule newR = new Rule(r.getPremise(), this.closure(r.getPremise()));
            newR.removeAllFromConclusion(newR.getPremise());
            if (!r.equals(newR)) {
                this.replaceRule(r, newR);
            }
        }
        return s - this.nbRules();
    }

    /**
     * Makes this component a left minimal and compact ImplicationalSystem.
     *
     * The unary form of this componant is first computed: if two rules have the
     * same unary conclusion, the rule with the inclusion-maximal premise is deleted.
     *
     * Then, the left-minimal treatment is performed in O(|sigma|^2|S|))
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeLeftMinimal() {
        this.makeUnary();
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r1 : sauv.sigma) {
            for (Rule r2 : sauv.sigma) {
                if (!r1.equals(r2)) {
                    if ((r2.getPremise().containsAll(r1.getPremise())) && (r1.getConclusion().equals(r2.getConclusion()))) {
                        this.sigma.remove(r2);
                    }
                }
            }
        }
        this.makeCompact();
        return sauv.nbRules() - this.nbRules();
    }

    /**
     * Makes this component a compact and direct ImplicationalSystem.
     *
     * The unary and proper form of this componant is first computed.
     * For two given rules r1 and r2, if the conclusion of r1 contains the premise of r1,
     * then a new rule is addes, with r1.premisse + r2.premisse - r1.conclusion as premise, and
     * r2.conclusion as conlusion. This treatment is performed in a recursive way until no new rule
     * is added.
     *
     * This treatment is performed in O(d|S|), where d  corresponds to the number of rules
     * that have to be added by the direct treatment, that can be exponential in the worst case.
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeDirect() {
        this.makeUnary();
        this.makeProper();
        int s = this.nbRules();
        boolean ok = true;
        while (ok) {
            ImplicationalSystem sauv = new ImplicationalSystem(this);
            for (Rule r1 : sauv.sigma) {
                for (Rule r2 : sauv.sigma) {
                    if (!r1.equals(r2) && !r1.getPremise().containsAll(r2.getConclusion())) {
                        ComparableSet  c = new ComparableSet(r2.getPremise());
                        c.removeAll(r1.getConclusion());
                        c.addAll(r1.getPremise());
                        if (!c.containsAll(r2.getPremise())) {
                            Rule newR  = new Rule(c, r2.getConclusion());
                            // new_r.addAllToPremise (r1.getPremise());
                            // new_r.addAllToPremise (r2.getPremise());
                            // new_r.removeAllFromPremise(r1.getConclusion());
                            // new_r.addAllToConclusion(r2.getConclusion() );
                            this.addRule(newR);
                        }
                    }
                }
            }
            if (this.nbRules() == sauv.nbRules()) {
                ok = false;
            }
        }
        this.makeCompact();
        return s - this.nbRules();
    }

    /**
     * Makes this component a minimum and proper ImplicationalSystem.
     *
     * A rule is deleted when the closure of its premisse remains the same
     * even if this rule is suppressed.
     *
     * This treatment is performed in O(|sigma||S|cl) where O(cl) is the
     * computation of a closure.
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeMinimum() {
        this.makeRightMaximal();
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r : sauv.sigma) {
            ImplicationalSystem epsylon = new ImplicationalSystem(this);
            epsylon.removeRule(r);
            if (epsylon.closure(r.getPremise()).equals(this.closure(r.getPremise()))) {
                this.removeRule(r);
            }
        }
        return sauv.nbRules() - this.nbRules();
    }

    /**
     * Replace this component by its canonical direct basis.
     *
     * The proper, unary and left minimal form of this component is first computed,
     * before to apply the recursive directe treatment, then the left minimal treatment.
     *
     * This treatment is performed in O(d), where d corresponds to the number of rules
     * that have to be added by the direct treatment. This number is exponential in the worst case.
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeCanonicalDirectBasis() {
        int s = this.nbRules();
        this.makeProper();
        this.makeLeftMinimal();
        this.makeDirect();
        this.makeLeftMinimal();
        this.makeCompact();
        return s - this.nbRules();
    }

    /**
     * Replace this component by the canonical basis.
     *
     * Conclusion of each rule is first replaced by its closure.
     * Then, premise of each rule r is replaced by its closure in ImplicationalSystem \ r.
     * This treatment is performed in (|Sigma||S|cl) where O(cl) is the
     * computation of a closure.
     *
     * @return  the difference between the number of rules of this component before and after this treatment
     */
    public int makeCanonicalBasis() {
        this.makeMinimum();
        ImplicationalSystem sauv = new ImplicationalSystem(this);
        for (Rule r : sauv.sigma) {
            ImplicationalSystem epsylon = new ImplicationalSystem(this);
            epsylon.removeRule(r);
            Rule tmp = new Rule(epsylon.closure(r.getPremise()), r.getConclusion());
            if (!r.equals(tmp)) {
                this.replaceRule(r, tmp);
            }
        }
        this.makeProper();
        return sauv.nbRules() - this.nbRules();
    }

    /* --------------- METHODS BASED ON GRAPH ------------ */

    /**
     * Returns the representative graph of this component.
     *
     * Nodes of the graph are attributes of this components.
     * For each proper rule X+b->a, there is an {X}-valuated edge from a to b.
     * Notice that, for a rule b->a, the edge from a to b is valuated by emptyset.
     * and for the two rules X+b->a and Y+b->a, the edge from a to b is valuated by {X,Y}.
     *
     * @return  the representative graph of this component.
     */
    public DGraph representativeGraph() {
        ImplicationalSystem tmp = new ImplicationalSystem(this);
        tmp.makeUnary();
        // nodes of the graph are elements not belonging to X
        DGraph pred = new DGraph();
        TreeMap<Comparable, Node> nodeCreated = new TreeMap<Comparable, Node>();
        for (Comparable x : tmp.getSet()) {
            Node n = new Node(x);
            pred.addNode(n);
            nodeCreated.put(x, n);
        }
        // an edge is added from b to a when there exists a rule X+a -> b or a -> b
        for (Rule r : tmp.getRules()) {
            for (Comparable a : r.getPremise()) {
                ComparableSet diff = new ComparableSet(r.getPremise());
                diff.remove(a);
                Node from = nodeCreated.get(r.getConclusion().first());
                Node to = nodeCreated.get(a);
                Edge ed;
                if (pred.containsEdge(from, to)) {
                    ed = pred.getEdge(from, to);
                } else {
                    ed = new Edge(from, to, new TreeSet<ComparableSet>());
                    pred.addEdge(ed);
                }
                ((TreeSet<ComparableSet>) ed.getContent()).add(diff);
            }
        }
        return pred;
    }

    /**
     * Returns the dependency graph of this component.
     *
     * Dependency graph of this component is the representative
     * graph of the canonical direct basis.
     * Therefore, the canonical direct basis has to be generated before
     * to compute its representativ graph, and
     * this treatment is performed in O(d), as for the canonical direct basis generation,
     * where d corresponds to the number of rules
     * that have to be added by the direct treatment. This number is exponential in the worst case.
     *
     * @return  the dependency graph of this component.
     */
    public DGraph dependencyGraph() {
        ImplicationalSystem bcd = new ImplicationalSystem(this);
        bcd.makeCanonicalDirectBasis();
        bcd.makeUnary();
        return bcd.representativeGraph();
    }

    /**
     * Removes from this component reducible elements.
     *
     * Reducible elements are elements equivalent by closure to others elements.
     * They are computed by `getReducibleElements` of `ClosureSystem`
     * in O(O(|Sigma||S|^2)
     *
     * @return  the set of reducibles removed elements, with their equivalent elements
     */
    public TreeMap<Comparable, TreeSet<Comparable>> reduction() {
        // compute the reducible elements
        TreeMap red = this.getReducibleElements();
        // modify each rule
        for (Object x : red.keySet()) {
            TreeSet<Rule> rules = this.getRules();
            rules = (TreeSet<Rule>) rules.clone();
            for (Rule r : rules) {
                Rule r2 = new Rule();
                boolean modif = false;
                // replace the reducible element by its equivalent in the premise
                TreeSet premise = r.getPremise();
                premise = (TreeSet) premise.clone();
                if (premise.contains(x)) {
                    premise.remove(x);
                    premise.addAll((TreeSet) red.get(x));
                    r2.addAllToPremise(premise);
                    modif = true;
                } else {
                    r2.addAllToPremise(premise);
                }
                // replace the reducible element by its equivalent in the conclusion
                TreeSet conclusion = r.getConclusion();
                conclusion = (TreeSet) conclusion.clone();
                if (conclusion.contains(x)) {
                    conclusion.remove(x);
                    conclusion.addAll((TreeSet) red.get(x));
                    r2.addAllToConclusion(conclusion);
                    modif = true;
                } else {
                    r2.addAllToConclusion(conclusion);
                }
                // replace the rule if modified
                if (modif) {
                    this.replaceRule(r, r2);
                }
            }
            // remove the reducible elements from the elements set
            this.deleteElement((Comparable) x);
        }
        return red;
    }

    /* --------------- IMPLEMENTATION OF CLOSURESYSTEM ABSTRACT METHODS ------------ */

    /**
     * Builds the closure of a set X of indexed elements.
     *
     * The closure is initialized with X. The closure is incremented with
     * the conclusion of each rule whose premise is included in it.
     * Iterations over the rules are performed until no new elemnet has to be added
     * in the closure.
     *
     * For direct ImplicationalSystem, only one iteration is needed, and the treatment is
     * performed in O(|Sigma||S|).
     *
     * For non direct ImplicationalSystem, at most |S| iterations are needed, and this tratment
     * is performed in O(|Sigma||S|^2).
     *
     * @param   x  a TreeSet of indexed elements
     *
     * @return  the closure of X for this component
     */
    public TreeSet<Comparable> closure(TreeSet<Comparable> x) {
        TreeSet<Comparable> oldES = new TreeSet<Comparable>();
        // all the attributes are in their own closure
        TreeSet<Comparable> newES = new TreeSet<Comparable>(x);
        do {
            oldES.addAll(newES);
            for (Rule r : this.sigma) {
                if (newES.containsAll(r.getPremise())) {
                    newES.addAll(r.getConclusion());
                }
            }
        } while (!(oldES.equals(newES)));
        return newES;
    }
}

