package lattice {
    class ImplicationalSystemReaderFactory {
    	-{static}HashMap<String, ImplicationalSystemReader> readers
        +{static}ImplicationalSystemReader register(ImplicationalSystemReader reader, String extension)
        +{static}ImplicationalSystemReader unregister(String extension)
        +{static}ImplicationalSystemReader get(String extension)
    }

    ImplicationalSystemReaderFactory o-- ImplicationalSystemReader
}
