package fr.kbertet.lattice.io {
    class ContextWriterText {
    	-{static}ContextWriterText instance
        +void write(Context context, BufferedWriter file)
        +{static}ContextWriterText getInstance()
        +{static}void register()
    }

    ContextWriter <|-- ContextWriterText
}
