package org.thegalactic.lattice {
    class BijectiveComponents {
        -ClosureSystem init
        -ConceptLattice lattice
        -Lattice reducedLattice
        -DGraph dependencyGraph
        -TreeSet<ComparableSet> minimalGenerators
        -ImplicationalSystem canonicalDirectBasis
        -ImplicationalSystem canonicalBasis
        -Context table
        .. Constructors ..
        +BijectiveComponents(ClosureSystem init)
        .. Computation ..
        +long compute()
        .. Initialisation ..
        +BijectiveComponents initialise()
        .. Persistence ..
        +void save(String directory, String name)
        .. Accessors ..
        +ClosureSystem getInit()
        +ConceptLattice getLattice()
        +Lattice getReducedLattice()
        +DGraph getDependencyGraph()
        +TreeSet<ComparableSet> getMinimalGenerators()
        +ImplicationalSystem getCanonicalDirectBasis()
        +ImplicationalSystem getCanonicalBasis()
        +Context getTable()
        .. Mutators ..
        #BijectiveComponents setInit(ClosureSystem init)
        #BijectiveComponents setLattice(ConceptLattice lattice)
        #BijectiveComponents setReducedLattice(Lattice reducedLattice)
        #BijectiveComponents setDependencyGraph(DGraph dependencyGraph)
        #BijectiveComponents setMinimalGenerators(TreeSet<ComparableSet> minimalGenerators)
        #BijectiveComponents setCanonicalDirectBasis(ImplicationalSystem canonicalDirectBasis)
        #BijectiveComponents setCanonicalBasis(ImplicationalSystem canonicalBasis)
        #BijectiveComponents setTable(Context table)
    }

    BijectiveComponents *-- "1" ClosureSystem
}
