package org.thegalactic.lattice {
    class Lattice {
        -DGraph dependencyGraph
        .. Constructors ..
        +Lattice()
        +Lattice(TreeSet<Node> set)
        +Lattice(DAGraph graph)
        .. Predicates ..
        +boolean isLattice()
        +boolean isCN()
        +boolean isAtomistic()
        +boolean isCoAtomistic()
        .. Operations ..
        +Node top()
        +Node bottom()
        +Node meet(Node x, Node y)
        +Node join(Node x, Node y)

        +TreeSet<Node> joinIrreducibles()
        +TreeSet<Node> meetIrreducibles()
        +TreeSet<Comparable> joinIrreducibles(Node node)
        +TreeSet<Comparable> meetIrreducibles(Node node)
        +DAGraph joinIrreduciblesSubgraph()
        +DAGraph meetIrreduciblesSubgraph()
        +DAGraph irreduciblesSubgraph()
        +ConceptLattice joinClosure()
        +ConceptLattice meetClosure()
        +ConceptLattice irreducibleClosure()
        +ComparableSet joinClosure(ComparableSet s)
        +ComparableSet meetClosure(ComparableSet s)
        +ComparableSet fullClosure(ComparableSet s)
        +TreeSet<ComparableSet> hybridGenerators()
        +Context getTable()
        +ImplicationalSystem getImplicationalSystem()

        +DGraph getDependencyGraph()
        #Lattice setDependencyGraph(DGraph graph)
        #hasDependencyGraph()
        +ImplicationalSystem getCanonicalDirectBasis()
        +TreeSet getMinimalGenerators()
        +ArrowRelation getArrowRelation()
    }

    DAGraph <|-- Lattice
}

